// src/lib/naver/origin-codes-full.ts
// AUTO-GENERATED from origin-codes.xls (518 entries)
// DO NOT EDIT MANUALLY

export interface OriginCodeEntry {
  code: string;
  label: string;
  region: string;
  importer: boolean;
}

export const ORIGIN_CODES_FULL: OriginCodeEntry[] = [
  // --- Special (4 items) ---
  { code: '00', label: '국산', region: 'SPECIAL', importer: false },
  { code: '03', label: '상세설명에 표시', region: 'SPECIAL', importer: false },
  { code: '04', label: '직접입력', region: 'SPECIAL', importer: false },
  { code: '05', label: '원산지 표기 의무대상 아님', region: 'SPECIAL', importer: false },

  // --- Domestic - Province Level (17 items) ---
  { code: '0001', label: '강원도', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0002', label: '경기도', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0003', label: '경상남도', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0004', label: '경상북도', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0005', label: '광주광역시', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0006', label: '대구광역시', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0007', label: '대전광역시', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0008', label: '부산광역시', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0009', label: '서울특별시', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0010', label: '울산광역시', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0011', label: '인천광역시', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0012', label: '전라남도', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0013', label: '전라북도', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0014', label: '제주특별자치도', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0015', label: '충청남도', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0016', label: '충청북도', region: 'DOMESTIC_PROVINCE', importer: false },
  { code: '0017', label: '세종특별자치시', region: 'DOMESTIC_PROVINCE', importer: false },

  // --- Domestic - City/District Level (263 items) ---
  { code: '0001110', label: '춘천시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001130', label: '원주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001150', label: '강릉시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001170', label: '동해시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001190', label: '태백시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001210', label: '속초시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001230', label: '삼척시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001720', label: '홍천군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001730', label: '횡성군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001750', label: '영월군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001760', label: '평창군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001770', label: '정선군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001780', label: '철원군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001790', label: '화천군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001800', label: '양구군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001810', label: '인제군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001820', label: '고성군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0001830', label: '양양군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002110', label: '수원시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002111', label: '수원시 장안구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002113', label: '수원시 권선구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002115', label: '수원시 팔달구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002117', label: '수원시 영통구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002130', label: '성남시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002131', label: '성남시 수정구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002133', label: '성남시 중원구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002135', label: '성남시 분당구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002150', label: '의정부시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002170', label: '안양시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002171', label: '안양시 만안구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002173', label: '안양시 동안구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002190', label: '부천시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002192', label: '부천시 원미구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002194', label: '부천시 소사구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002196', label: '부천시 오정구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002210', label: '광명시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002220', label: '평택시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002250', label: '동두천시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002270', label: '안산시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002271', label: '안산시 상록구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002273', label: '안산시 단원구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002280', label: '고양시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002281', label: '고양시 덕양구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002285', label: '고양시 일산동구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002287', label: '고양시 일산서구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002290', label: '과천시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002310', label: '구리시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002360', label: '남양주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002370', label: '오산시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002390', label: '시흥시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002410', label: '군포시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002430', label: '의왕시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002450', label: '하남시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002460', label: '용인시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002461', label: '용인시 처인구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002463', label: '용인시 기흥구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002465', label: '용인시 수지구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002480', label: '파주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002500', label: '이천시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002550', label: '안성시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002570', label: '김포시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002590', label: '화성시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002610', label: '광주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002630', label: '양주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002650', label: '포천시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002670', label: '여주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002800', label: '연천군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002820', label: '가평군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0002830', label: '양평군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003120', label: '창원시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003121', label: '창원시 의창구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003123', label: '창원시 성산구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003125', label: '창원시 마산합포구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003127', label: '창원시 마산회원구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003129', label: '창원시 진해구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003170', label: '진주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003220', label: '통영시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003240', label: '사천시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003250', label: '김해시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003270', label: '밀양시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003310', label: '거제시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003330', label: '양산시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003720', label: '의령군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003730', label: '함안군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003740', label: '창녕군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003820', label: '고성군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003840', label: '남해군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003850', label: '하동군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003860', label: '산청군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003870', label: '함양군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003880', label: '거창군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0003890', label: '합천군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004110', label: '포항시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004111', label: '포항시 남구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004113', label: '포항시 북구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004130', label: '경주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004150', label: '김천시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004170', label: '안동시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004190', label: '구미시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004210', label: '영주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004230', label: '영천시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004250', label: '상주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004280', label: '문경시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004290', label: '경산시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004730', label: '의성군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004750', label: '청송군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004760', label: '영양군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004770', label: '영덕군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004820', label: '청도군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004830', label: '고령군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004840', label: '성주군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004850', label: '칠곡군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004900', label: '예천군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004920', label: '봉화군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004930', label: '울진군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0004940', label: '울릉군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0005110', label: '동구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0005140', label: '서구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0005155', label: '남구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0005170', label: '북구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0005200', label: '광산구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0006110', label: '중구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0006140', label: '동구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0006170', label: '서구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0006200', label: '남구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0006230', label: '북구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0006260', label: '수성구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0006290', label: '달서구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0006710', label: '달성군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0006720', label: '군위군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0007110', label: '동구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0007140', label: '중구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0007170', label: '서구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0007200', label: '유성구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0007230', label: '대덕구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008110', label: '중구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008140', label: '서구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008170', label: '동구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008200', label: '영도구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008230', label: '부산진구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008260', label: '동래구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008290', label: '남구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008320', label: '북구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008350', label: '해운대구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008380', label: '사하구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008410', label: '금정구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008440', label: '강서구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008470', label: '연제구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008500', label: '수영구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008530', label: '사상구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0008710', label: '기장군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009110', label: '종로구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009140', label: '중구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009170', label: '용산구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009200', label: '성동구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009215', label: '광진구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009230', label: '동대문구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009260', label: '중랑구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009290', label: '성북구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009305', label: '강북구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009320', label: '도봉구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009350', label: '노원구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009380', label: '은평구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009410', label: '서대문구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009440', label: '마포구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009470', label: '양천구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009500', label: '강서구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009530', label: '구로구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009545', label: '금천구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009560', label: '영등포구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009590', label: '동작구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009620', label: '관악구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009650', label: '서초구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009680', label: '강남구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009710', label: '송파구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0009740', label: '강동구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0010110', label: '중구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0010140', label: '남구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0010170', label: '동구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0010200', label: '북구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0010710', label: '울주군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0011110', label: '중구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0011140', label: '동구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0011177', label: '미추홀구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0011185', label: '연수구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0011200', label: '남동구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0011237', label: '부평구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0011245', label: '계양구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0011260', label: '서구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0011710', label: '강화군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0011720', label: '옹진군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012110', label: '목포시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012130', label: '여수시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012150', label: '순천시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012170', label: '나주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012230', label: '광양시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012710', label: '담양군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012720', label: '곡성군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012730', label: '구례군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012770', label: '고흥군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012780', label: '보성군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012790', label: '화순군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012800', label: '장흥군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012810', label: '강진군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012820', label: '해남군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012830', label: '영암군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012840', label: '무안군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012860', label: '함평군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012870', label: '영광군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012880', label: '장성군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012890', label: '완도군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012900', label: '진도군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0012910', label: '신안군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013110', label: '전주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013111', label: '전주시 완산구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013113', label: '전주시 덕진구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013130', label: '군산시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013140', label: '익산시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013180', label: '정읍시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013190', label: '남원시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013210', label: '김제시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013710', label: '완주군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013720', label: '진안군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013730', label: '무주군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013740', label: '장수군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013750', label: '임실군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013770', label: '순창군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013790', label: '고창군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0013800', label: '부안군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0014110', label: '제주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0014130', label: '서귀포시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015130', label: '천안시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015131', label: '천안시 동남구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015133', label: '천안시 서북구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015150', label: '공주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015180', label: '보령시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015200', label: '아산시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015210', label: '서산시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015230', label: '논산시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015250', label: '계룡시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015270', label: '당진시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015710', label: '금산군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015760', label: '부여군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015770', label: '서천군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015790', label: '청양군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015800', label: '홍성군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015810', label: '예산군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0015825', label: '태안군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016110', label: '청주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016111', label: '청주시 상당구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016112', label: '청주시 서원구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016113', label: '청주시 흥덕구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016114', label: '청주시 청원구', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016130', label: '충주시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016150', label: '제천시', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016720', label: '보은군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016730', label: '옥천군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016740', label: '영동군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016745', label: '증평군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016750', label: '진천군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016760', label: '괴산군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016770', label: '음성군', region: 'DOMESTIC_CITY', importer: false },
  { code: '0016800', label: '단양군', region: 'DOMESTIC_CITY', importer: false },

  // --- Asia (Import) (50 items) ---
  { code: '0200000', label: '그루지야', region: 'ASIA', importer: true },
  { code: '0200001', label: '네팔', region: 'ASIA', importer: true },
  { code: '0200002', label: '대만', region: 'ASIA', importer: true },
  { code: '0200003', label: '동티모르', region: 'ASIA', importer: true },
  { code: '0200004', label: '라오스', region: 'ASIA', importer: true },
  { code: '0200005', label: '레바논', region: 'ASIA', importer: true },
  { code: '0200006', label: '리비아', region: 'ASIA', importer: true },
  { code: '0200007', label: '마카오', region: 'ASIA', importer: true },
  { code: '0200008', label: '말레이시아', region: 'ASIA', importer: true },
  { code: '0200009', label: '몰디브', region: 'ASIA', importer: true },
  { code: '0200010', label: '몽골', region: 'ASIA', importer: true },
  { code: '0200011', label: '미얀마', region: 'ASIA', importer: true },
  { code: '0200012', label: '바레인', region: 'ASIA', importer: true },
  { code: '0200013', label: '방글라데시', region: 'ASIA', importer: true },
  { code: '0200014', label: '베트남', region: 'ASIA', importer: true },
  { code: '0200015', label: '부탄', region: 'ASIA', importer: true },
  { code: '0200016', label: '북한', region: 'ASIA', importer: true },
  { code: '0200017', label: '브루나이', region: 'ASIA', importer: true },
  { code: '0200018', label: '사우디아라비아', region: 'ASIA', importer: true },
  { code: '0200019', label: '스리랑카', region: 'ASIA', importer: true },
  { code: '0200020', label: '시리아', region: 'ASIA', importer: true },
  { code: '0200021', label: '싱가포르', region: 'ASIA', importer: true },
  { code: '0200022', label: '아랍에미리트', region: 'ASIA', importer: true },
  { code: '0200023', label: '아르메니아', region: 'ASIA', importer: true },
  { code: '0200024', label: '아프가니스탄', region: 'ASIA', importer: true },
  { code: '0200025', label: '예멘', region: 'ASIA', importer: true },
  { code: '0200026', label: '오만', region: 'ASIA', importer: true },
  { code: '0200027', label: '요르단', region: 'ASIA', importer: true },
  { code: '0200028', label: '우즈베키스탄', region: 'ASIA', importer: true },
  { code: '0200029', label: '우크라이나', region: 'ASIA', importer: true },
  { code: '0200030', label: '이라크', region: 'ASIA', importer: true },
  { code: '0200031', label: '이란', region: 'ASIA', importer: true },
  { code: '0200032', label: '이스라엘', region: 'ASIA', importer: true },
  { code: '0200033', label: '인도', region: 'ASIA', importer: true },
  { code: '0200034', label: '인도네시아', region: 'ASIA', importer: true },
  { code: '0200035', label: '인도양식민지', region: 'ASIA', importer: true },
  { code: '0200036', label: '일본', region: 'ASIA', importer: true },
  { code: '0200037', label: '중국', region: 'ASIA', importer: true },
  { code: '0200038', label: '카자흐스탄', region: 'ASIA', importer: true },
  { code: '0200039', label: '카타르', region: 'ASIA', importer: true },
  { code: '0200040', label: '캄보디아', region: 'ASIA', importer: true },
  { code: '0200041', label: '쿠웨이트', region: 'ASIA', importer: true },
  { code: '0200042', label: '키리기스스탄', region: 'ASIA', importer: true },
  { code: '0200043', label: '타지키스탄', region: 'ASIA', importer: true },
  { code: '0200044', label: '태국', region: 'ASIA', importer: true },
  { code: '0200045', label: '투르크메니스탄', region: 'ASIA', importer: true },
  { code: '0200046', label: '티베트', region: 'ASIA', importer: true },
  { code: '0200047', label: '파키스탄', region: 'ASIA', importer: true },
  { code: '0200048', label: '필리핀', region: 'ASIA', importer: true },
  { code: '0200049', label: '홍콩', region: 'ASIA', importer: true },

  // --- Europe (Import) (51 items) ---
  { code: '0201000', label: '그리스', region: 'EUROPE', importer: true },
  { code: '0201001', label: '그린란드', region: 'EUROPE', importer: true },
  { code: '0201002', label: '네덜란드', region: 'EUROPE', importer: true },
  { code: '0201003', label: '노르웨이', region: 'EUROPE', importer: true },
  { code: '0201004', label: '덴마크', region: 'EUROPE', importer: true },
  { code: '0201005', label: '독일', region: 'EUROPE', importer: true },
  { code: '0201006', label: '라트비아', region: 'EUROPE', importer: true },
  { code: '0201007', label: '러시아연방', region: 'EUROPE', importer: true },
  { code: '0201008', label: '룩셈부르크', region: 'EUROPE', importer: true },
  { code: '0201009', label: '리투아니아', region: 'EUROPE', importer: true },
  { code: '0201010', label: '리히텐슈타인', region: 'EUROPE', importer: true },
  { code: '0201011', label: '마케도니아', region: 'EUROPE', importer: true },
  { code: '0201012', label: '말타', region: 'EUROPE', importer: true },
  { code: '0201013', label: '모나코', region: 'EUROPE', importer: true },
  { code: '0201014', label: '몰도바공화국', region: 'EUROPE', importer: true },
  { code: '0201015', label: '몰타', region: 'EUROPE', importer: true },
  { code: '0201016', label: '바티칸', region: 'EUROPE', importer: true },
  { code: '0201017', label: '벨기에', region: 'EUROPE', importer: true },
  { code: '0201018', label: '벨라루스', region: 'EUROPE', importer: true },
  { code: '0201019', label: '벨로루시', region: 'EUROPE', importer: true },
  { code: '0201020', label: '보스니아-헤르체고비나', region: 'EUROPE', importer: true },
  { code: '0201021', label: '불가리아', region: 'EUROPE', importer: true },
  { code: '0201022', label: '사이프러스', region: 'EUROPE', importer: true },
  { code: '0201023', label: '스웨덴', region: 'EUROPE', importer: true },
  { code: '0201024', label: '스위스', region: 'EUROPE', importer: true },
  { code: '0201025', label: '스페인', region: 'EUROPE', importer: true },
  { code: '0201026', label: '슬로바키아', region: 'EUROPE', importer: true },
  { code: '0201027', label: '슬로베니아', region: 'EUROPE', importer: true },
  { code: '0201028', label: '아이슬란드', region: 'EUROPE', importer: true },
  { code: '0201029', label: '아일랜드공화국', region: 'EUROPE', importer: true },
  { code: '0201030', label: '아제르바이잔', region: 'EUROPE', importer: true },
  { code: '0201031', label: '안도라', region: 'EUROPE', importer: true },
  { code: '0201032', label: '알메니아', region: 'EUROPE', importer: true },
  { code: '0201033', label: '알바니아', region: 'EUROPE', importer: true },
  { code: '0201034', label: '에스토니아', region: 'EUROPE', importer: true },
  { code: '0201035', label: '영국', region: 'EUROPE', importer: true },
  { code: '0201036', label: '오스트리아', region: 'EUROPE', importer: true },
  { code: '0201037', label: '유고', region: 'EUROPE', importer: true },
  { code: '0201038', label: '이탈리아', region: 'EUROPE', importer: true },
  { code: '0201039', label: '조지아', region: 'EUROPE', importer: true },
  { code: '0201040', label: '체코', region: 'EUROPE', importer: true },
  { code: '0201041', label: '크로아티아', region: 'EUROPE', importer: true },
  { code: '0201042', label: '터키', region: 'EUROPE', importer: true },
  { code: '0201043', label: '페로스제도', region: 'EUROPE', importer: true },
  { code: '0201044', label: '포르투갈', region: 'EUROPE', importer: true },
  { code: '0201045', label: '폴란드', region: 'EUROPE', importer: true },
  { code: '0201046', label: '프랑스', region: 'EUROPE', importer: true },
  { code: '0201047', label: '핀란드', region: 'EUROPE', importer: true },
  { code: '0201048', label: '헝가리', region: 'EUROPE', importer: true },
  { code: '0201049', label: '루마니아', region: 'EUROPE', importer: true },
  { code: '0201050', label: '세르비아', region: 'EUROPE', importer: true },

  // --- Africa (Import) (59 items) ---
  { code: '0202000', label: '가나', region: 'AFRICA', importer: true },
  { code: '0202001', label: '가봉', region: 'AFRICA', importer: true },
  { code: '0202002', label: '가이아나', region: 'AFRICA', importer: true },
  { code: '0202003', label: '감비아', region: 'AFRICA', importer: true },
  { code: '0202004', label: '기니', region: 'AFRICA', importer: true },
  { code: '0202005', label: '기니비사우', region: 'AFRICA', importer: true },
  { code: '0202006', label: '나미비아', region: 'AFRICA', importer: true },
  { code: '0202007', label: '나이지리아', region: 'AFRICA', importer: true },
  { code: '0202008', label: '남아프리카공화국', region: 'AFRICA', importer: true },
  { code: '0202009', label: '니제르', region: 'AFRICA', importer: true },
  { code: '0202010', label: '라이베리아', region: 'AFRICA', importer: true },
  { code: '0202011', label: '레소토', region: 'AFRICA', importer: true },
  { code: '0202012', label: '르완다', region: 'AFRICA', importer: true },
  { code: '0202013', label: '마다가스카르', region: 'AFRICA', importer: true },
  { code: '0202014', label: '마르티니크', region: 'AFRICA', importer: true },
  { code: '0202015', label: '말라위', region: 'AFRICA', importer: true },
  { code: '0202016', label: '말리', region: 'AFRICA', importer: true },
  { code: '0202017', label: '모로코', region: 'AFRICA', importer: true },
  { code: '0202018', label: '모리셔스', region: 'AFRICA', importer: true },
  { code: '0202019', label: '모리타니', region: 'AFRICA', importer: true },
  { code: '0202020', label: '모잠비크', region: 'AFRICA', importer: true },
  { code: '0202021', label: '베냉', region: 'AFRICA', importer: true },
  { code: '0202022', label: '보츠와나', region: 'AFRICA', importer: true },
  { code: '0202023', label: '부룬디', region: 'AFRICA', importer: true },
  { code: '0202024', label: '부르키나파소', region: 'AFRICA', importer: true },
  { code: '0202025', label: '사오토메프린시페', region: 'AFRICA', importer: true },
  { code: '0202026', label: '상투메 프린시페', region: 'AFRICA', importer: true },
  { code: '0202027', label: '서사하라', region: 'AFRICA', importer: true },
  { code: '0202028', label: '세네갈', region: 'AFRICA', importer: true },
  { code: '0202029', label: '세이셀', region: 'AFRICA', importer: true },
  { code: '0202030', label: '소말리아', region: 'AFRICA', importer: true },
  { code: '0202031', label: '수단', region: 'AFRICA', importer: true },
  { code: '0202032', label: '스와질랜드', region: 'AFRICA', importer: true },
  { code: '0202033', label: '시에라리온', region: 'AFRICA', importer: true },
  { code: '0202034', label: '알제리', region: 'AFRICA', importer: true },
  { code: '0202035', label: '앙골라', region: 'AFRICA', importer: true },
  { code: '0202036', label: '에티오피아', region: 'AFRICA', importer: true },
  { code: '0202037', label: '에리트리아', region: 'AFRICA', importer: true },
  { code: '0202038', label: '우간다', region: 'AFRICA', importer: true },
  { code: '0202039', label: '이집트', region: 'AFRICA', importer: true },
  { code: '0202040', label: '잠비아', region: 'AFRICA', importer: true },
  { code: '0202041', label: '적도기니공화국', region: 'AFRICA', importer: true },
  { code: '0202042', label: '중앙아프리카공화국', region: 'AFRICA', importer: true },
  { code: '0202043', label: '지부티', region: 'AFRICA', importer: true },
  { code: '0202044', label: '지브롤터', region: 'AFRICA', importer: true },
  { code: '0202045', label: '짐바브웨', region: 'AFRICA', importer: true },
  { code: '0202046', label: '차드', region: 'AFRICA', importer: true },
  { code: '0202047', label: '카메룬', region: 'AFRICA', importer: true },
  { code: '0202048', label: '카보베르데', region: 'AFRICA', importer: true },
  { code: '0202049', label: '케냐', region: 'AFRICA', importer: true },
  { code: '0202050', label: '코모로', region: 'AFRICA', importer: true },
  { code: '0202051', label: '코모로스', region: 'AFRICA', importer: true },
  { code: '0202052', label: '코트디브와르', region: 'AFRICA', importer: true },
  { code: '0202053', label: '콩고', region: 'AFRICA', importer: true },
  { code: '0202054', label: '콩고민주공화국', region: 'AFRICA', importer: true },
  { code: '0202055', label: '탄자니아', region: 'AFRICA', importer: true },
  { code: '0202056', label: '터크스앤카이코스제도', region: 'AFRICA', importer: true },
  { code: '0202057', label: '토고', region: 'AFRICA', importer: true },
  { code: '0202058', label: '튀니지', region: 'AFRICA', importer: true },

  // --- Oceania (Import) (26 items) ---
  { code: '0203000', label: '괌', region: 'OCEANIA', importer: true },
  { code: '0203001', label: '나우루', region: 'OCEANIA', importer: true },
  { code: '0203002', label: '노퍽아일랜드', region: 'OCEANIA', importer: true },
  { code: '0203003', label: '뉴질랜드', region: 'OCEANIA', importer: true },
  { code: '0203004', label: '뉴칼레도니아', region: 'OCEANIA', importer: true },
  { code: '0203005', label: '마리아나군도', region: 'OCEANIA', importer: true },
  { code: '0203006', label: '마셜군도', region: 'OCEANIA', importer: true },
  { code: '0203007', label: '마이크로네시아', region: 'OCEANIA', importer: true },
  { code: '0203008', label: '미크로네시아', region: 'OCEANIA', importer: true },
  { code: '0203009', label: '바누아투', region: 'OCEANIA', importer: true },
  { code: '0203010', label: '서사모아', region: 'OCEANIA', importer: true },
  { code: '0203011', label: '세인트빈센트', region: 'OCEANIA', importer: true },
  { code: '0203012', label: '솔로몬군도', region: 'OCEANIA', importer: true },
  { code: '0203013', label: '아메리칸사모아', region: 'OCEANIA', importer: true },
  { code: '0203014', label: '코코스섬', region: 'OCEANIA', importer: true },
  { code: '0203015', label: '쿡아일랜드', region: 'OCEANIA', importer: true },
  { code: '0203016', label: '크리스마스섬', region: 'OCEANIA', importer: true },
  { code: '0203017', label: '키리바시', region: 'OCEANIA', importer: true },
  { code: '0203018', label: '통가', region: 'OCEANIA', importer: true },
  { code: '0203019', label: '투발루', region: 'OCEANIA', importer: true },
  { code: '0203020', label: '파푸아뉴기니', region: 'OCEANIA', importer: true },
  { code: '0203021', label: '팔라우', region: 'OCEANIA', importer: true },
  { code: '0203022', label: '폴리네시아(프랑스령)', region: 'OCEANIA', importer: true },
  { code: '0203023', label: '피지', region: 'OCEANIA', importer: true },
  { code: '0203024', label: '호주', region: 'OCEANIA', importer: true },
  { code: '0203025', label: '후투나', region: 'OCEANIA', importer: true },

  // --- North America (Import) (7 items) ---
  { code: '0204000', label: '미국', region: 'NORTH_AMERICA', importer: true },
  { code: '0204001', label: '바베이도스', region: 'NORTH_AMERICA', importer: true },
  { code: '0204002', label: '세인트 빈센트 그레나딘', region: 'NORTH_AMERICA', importer: true },
  { code: '0204003', label: '아이티', region: 'NORTH_AMERICA', importer: true },
  { code: '0204004', label: '앤티가 바부다', region: 'NORTH_AMERICA', importer: true },
  { code: '0204005', label: '유에스버진아일랜드', region: 'NORTH_AMERICA', importer: true },
  { code: '0204006', label: '캐나다', region: 'NORTH_AMERICA', importer: true },

  // --- South America (Import) (41 items) ---
  { code: '0205000', label: '과델루페', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205001', label: '과테말라', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205002', label: '그레나다', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205003', label: '네비스', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205004', label: '니카라과', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205005', label: '도미니카', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205006', label: '도미니카공화국', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205007', label: '멕시코', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205008', label: '몬체라트', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205009', label: '바바도스', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205010', label: '바하마', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205011', label: '버뮤다', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205012', label: '베네수엘라', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205013', label: '벨리제', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205014', label: '볼리비아', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205015', label: '브라질', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205016', label: '브리티시 버진아일랜드', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205017', label: '세인트루시아', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205018', label: '수리남', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205019', label: '아루바', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205020', label: '아르헨티나', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205021', label: '아센션 이스난드', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205022', label: '안티구아', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205023', label: '앙길라', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205024', label: '에콰도르', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205025', label: '엘살바도르', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205026', label: '온두라스', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205027', label: '우루과이', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205028', label: '자메이카', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205029', label: '칠레', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205030', label: '코스타리카', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205031', label: '콜롬비아', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205032', label: '쿠바', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205033', label: '트리니다드토바고', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205034', label: '파나마', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205035', label: '파라과이', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205036', label: '페루', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205037', label: '포크랜드', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205038', label: '푸에르토리코', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205039', label: '프랑스령 기아나', region: 'SOUTH_AMERICA', importer: true },
  { code: '0205040', label: '하이티', region: 'SOUTH_AMERICA', importer: true },
];

// Total: 518 origin codes
// Domestic: 280, Import: 234, Special: 4

// Quick lookup by code
export const ORIGIN_CODE_MAP = new Map<string, OriginCodeEntry>(
  ORIGIN_CODES_FULL.map(o => [o.code, o])
);

// Check if origin requires importer field
export function requiresImporter(code: string): boolean {
  const entry = ORIGIN_CODE_MAP.get(code);
  return entry?.importer ?? false;
}

// Get display label with region prefix for search
export function getOriginDisplayLabel(code: string): string {
  const entry = ORIGIN_CODE_MAP.get(code);
  if (!entry) return code;
  if (entry.region === 'SPECIAL') return entry.label;
  if (entry.region.startsWith('DOMESTIC')) return `domestic > ${entry.label}`;
  return `import > ${entry.label}`;
}